config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # See all Tasks
  get '/tasks', to: 'tasks#index'

  # Create a Task
  ## display the form
  get '/tasks/new', to: 'tasks#new', as: :new_task
  ## Post new info in the DB
  post '/tasks', to: 'tasks#create'

  # Update a Task
  ## Display the form
  get '/tasks/:id/edit', to: 'tasks#edit', as: :mango
  ## Post information into DB
  patch '/tasks/:id', to: 'tasks#update'

  # See one Task
  get '/tasks/:id', to: 'tasks#show', as: :task

  # Delete a Task
  delete '/tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div>
  <%= form_for(task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="tasksdashboard">
  <h1>All My Tasks</h1>

  <ul class="alltasks">
    <% @tasks.each do |task| %>
    <li>

      <% if task.completed == false %>
        <i class="far fa-square"> | </i>
      <% else %>
        <i class="far fa-check-square"> | </i>
      <% end %>

        <%= link_to task.title, task_path(task), :class => 'tasktitle' %>

    </li>
    <% end %>
  </ul>

  <i class="fas fa-plus"></i> | <%= link_to "Create new Task", new_task_path, :class => 'tasktitle' %>
</div>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h4><%= @task.details %></h4>

<p>
   <%=
    if @task.completed == false
      "[ ] - This task is not completed"
    else
      "[X] - This task is completed"
    end
  %>
</p>

<%= link_to "Go back", tasks_path %>
<%= link_to "edit task", mango_path(@task)  %>
<%= link_to 'destroy', task_path(@task), method: :delete, data: {confirm: "Are you sure?"} %>